### PR TITLE
Fixed issue with title (added empty space)

### PR DESCRIPTION
**Pull request by doekon**

### CODE REVIEW

**Comment by cscheid** [comment]
@doekon, I'm not a fan of the inconsistent dashes and underscores in the URL. Is there a particular reason for that?

**Comment by doekon** [comment]
I think I was trying to separate the higher level name "practioner-guide" from the names of the subpages in my file names (for storing them locally on my computer). I was not aware at this time that this would be the URL then as well. So please feel free to change it to whatever seems best for you.

**Comment by cscheid** [comment]
Ok, got it.

What do you think about, instead of `/year/2017/info/overview-amp-topics/practitioner-guide_data-journalists`, we go with `/year/2017/info/practitioner-guide/data-journalists`? We've been trying to get rid of that ugly "overview-amp-topics" folder that exists only for legacy reasons.

**Comment by doekon** [comment]
Fine with me. Thanks!


Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Carlos Scheidegger <notifications@github.com> Datum: 07.09.17  19:44  (GMT+01:00) An: "ieee-vgtc/ieeevis.org" <ieeevis.org@noreply.github.com> Cc: doekon <doekon@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [ieee-vgtc/ieeevis.org] Fixed issue with title (added empty
  space) (#275) 
Ok, got it.
What do you think about, instead of /year/2017/info/overview-amp-topics/practitioner-guide_data-journalists, we go with /year/2017/info/practitioner-guide/data-journalists? We've been trying to get rid of that ugly "overview-amp-topics" folder that exists only for legacy reasons.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ieee-vgtc/ieeevis.org","title":"ieee-vgtc/ieeevis.org","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ieee-vgtc/ieeevis.org"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cscheid in #275: Ok, got it.\r\n\r\nWhat do you think about, instead of `/year/2017/info/overview-amp-topics/practitioner-guide_data-journalists`, we go with `/year/2017/info/practitioner-guide/data-journalists`? We've been trying to get rid of that ugly \"overview-amp-topics\" folder that exists only for legacy reasons."}],"action":{"name":"View Pull Request","url":"https://github.com/ieee-vgtc/ieeevis.org/pull/275#issuecomment-327867805"}}}

**Pull request merged**
