### PR TITLE
Update vis-executive-committee.md

### PR DESCRIPTION
**Pull request by sobieavila**
missing comma after City in Jason's affiliation

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks - This still doesn't exactly match 2017's affiliation. Is that on purpose?

    | Jason Dykes	| *City, University of London*

vs

    | Jason Dykes | *City, University London<br>(InfoVis Steering Rep.)*

**Comment by sobieavila** [comment]
Sorry - caught the missing comma and not the missing "of". Yes, please make
it "City, University of London". Thanks!

**Comment by codementum** [comment]
I made the "of" change

**Comment by sobieavila** [comment]
Thanks!

Lisa

**Pull request merged**
