### PR TITLE
Create doctoral_colloquium.md

### PR DESCRIPTION
**Pull request by ttekusov**

### CODE REVIEW

**Comment by cscheid** [comment]
This looks good, thanks.

**Comment by cscheid** [comment]
Actually, @ttekusov, I do have a few requests. Can you format this in the style of http://ieeevis.org/year/2016/info/call-participation/doctoral-colloquium ?

For example:

* heading titles are all-caps
* Important dates in a separate section with a table

You can use that [file as an example](https://github.com/ieee-vgtc/ieeevis.org/blob/master/year/2016/info/call-participation/doctoral_colloquium.md)

**Comment by ttekusov** [comment]
Hi Carlos,

during editing in github, I see the file only as a plain text, I have no clue how to format it correctly.

When I saw the final file, it looked formatted. I have no clue how this works.

I feel responsible for content of web, not for the web programming.

Tatiana

**Comment by ttekusov** [comment]
Dear Carlos,
I changed the titles so that they match 2016, I also included Important dates section so that it matches 2016, I do not know how to do the formatting of important dates in a table. Could you please either do it or advise me how to do it?

Thanks
Best
Tatiana

**Pull request merged**
