### PR TITLE
added ViP - Vis in the Wild

### PR DESCRIPTION
**Pull request by bhentschel**
Added abstract for the ViP Workshop component and link to new ViP web page.

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks, Bernd! I'll just confirm with workshops chairs that this change is OK with them.

@lindstro, @remcochang: If you reply with "ok", I'll go ahead and merge.

**Comment by remcochang** [comment]
I can't remember what we're oking...  But sure!  OK!  :D


Remco

--
Remco Chang
Associate Professor
Department of Computer Science
Tufts University
http://www.cs.tufts.edu/~remco
(office) 617-627-3681
(lab)    617-627-6514

**Comment by bhentschel** [comment]
@remcochang You just ok'ed that the Vis In Practice workshop announcement gets linked along with the "regular workshops". Thanks!

**Comment by remcochang** [comment]
Oh yeah, of course!  :)


Remco

--
Remco Chang
Associate Professor
Department of Computer Science
Tufts University
http://www.cs.tufts.edu/~remco
(office) 617-627-3681
(lab)    617-627-6514

**Comment by cscheid** [comment]
Thanks, folks.

**Pull request merged**
