### PR TITLE
Create future-locations-ieee-vis-conferences

### PR DESCRIPTION
**Pull request by mhaley1979**
Add future years page to 
- website
- main menu

### CODE REVIEW

**Comment by cscheid** [comment]
This looks great, aside from a very minor suggestion.

What about just "future-locations" instead of "future-locations-ieee-vis-conferences"?

**Comment by mhaley1979** [comment]
Yes, future-locations works well. Thanks.

**Comment by cscheid** [comment]
It's on staging now.

**Comment by mhaley1979** [comment]
Ta!

**Pull request merged**
