### PR TITLE
Use bundler to install ruby dependencies and fix npm dependencies

### PR DESCRIPTION
**Pull request by domoritz**
When I tried to run the website, I found that the package.json had incompatible versions so I fixed them. I also added support for bundler so that one doesn't need to install Jekyll globally. Plus, you now get a lock file for the rust dependencies so that everyone gets consistent dependencies.

### CODE REVIEW

**Comment by yelper** [comment]
FYI, similar changes need to be made to vis2019/vis2020/vis2021 branches to maintain build similarity.  Otherwise, dependencies will diverge while building the whole website.

**Comment by domoritz** [comment]
I'm not sure I agree. The other branches are not locking any ruby dependencies so they should not break with these dependencies if they are not broken already with new Jekyll versions.

I agree, though, that it would be good to keep a similar build process. To make it easier to back port the ruby changes, I split the commits. I can send PRs with 54b5b5aa719972206f5fbe611e138e9037f4c76c cherry picked on top of the other branches.

**Comment by domoritz** [comment]
https://github.com/ieee-vgtc/ieeevis.org/pull/1474
https://github.com/ieee-vgtc/ieeevis.org/pull/1475
https://github.com/ieee-vgtc/ieeevis.org/pull/1476

**Comment by dylancashman** [comment]
This looks right to me.  It makes sense to use the bundled environment.  Thanks @domoritz.   I'll test the other environments, good thinking @yelper.

**Review by dylancashman — APPROVED** [review]

**Pull request merged**
