### PR TITLE
Add final reVISe blog posts

### PR DESCRIPTION
**Pull request by cgarth**
This adds the final reVISe blog posts, plus fixes for the governance blog post.

### CODE REVIEW

**Comment by yelper** [comment]
We will have to also port these changes to VIS 2021 when it goes live.  I'll make a task for myself.

**Comment by spetruzza** [comment]
There is a file missing file pointed by the 2020-10-25-Governance.md page, it is called "governance_model_figure.pdf", @cgarth please add this file to "assets/posts/" and adjust the path to the file accordingly in the page.

**Comment by cgarth** [comment]
I was just debugging this.

Your rename of “2020-11-1-Governance.md” (f249296) collided with my rename of the same file. Now the both posts have the same permalink, which is why only the old/unfixed one is showing up. Please simply remove "2020-10-25-Governance.md". (I'm happy to send a PR.)

**Comment by spetruzza** [comment]
OK I can remove that one

**Comment by cgarth** [comment]
Look good. Thanks!

**Pull request merged**
