### PR TITLE
Fixing panelists for accessibility panel

### PR DESCRIPTION
**Pull request by arvind**
/cc @mcorrell

### CODE REVIEW

**Comment by mcorrell** [comment]
@mbehrisch can you confirm the other panels have the right listing of organizers/panelists?

**Comment by spetruzza** [comment]
@arvind @mcorrell please let us know if the changes are confirmed and this can be merged, thank you

**Comment by arvind** [comment]
These changes are confirmed for the panel that I'm co-organizing. I can't speak to the other panels here. My preference would be to merge this sooner rather than later, since our panel's information has been listed incorrectly for a few weeks now. Thank you :)

**Comment by spetruzza** [comment]
Merged, you can always open a new PR one to fix the rest, if needed

**Comment by arvind** [comment]
Thank you 🙏

**Pull request merged**
