### PR TITLE
2017 VAST Challenge Awards / Workshop page

### PR DESCRIPTION
**Pull request by whiting-vastchallenge**
Hi Web folk!  Hope this came through OK!  It's an update from the 2016 version of this page for 2017.  Let me know if you need something else from me on it.  Thanks! -Mark Whiting 
mark.whiting@pnnl.gov

### CODE REVIEW

**Comment by cscheid** [comment]
Do you want to call the page "vast challenge awards"? I ask because it seems to more about the VAST Challenge more than the awards themselves.

@RossMaciejewski, @jamesAhrens - here's a new page for you to review, as per our agreed workflow of "new page, chairs must review; updates, chairs don't review".

**Comment by cscheid** [comment]
(@whiting-vastchallenge, thank you for helping with adding the content directly! It looks pretty good. We'll merge it when we get the ok from Jim and Ross)

**Comment by RossMaciejewski** [comment]
I'm ok w/ merging. Need to link to the sidebar as well. Did the challenge
awards link need a name change?

On Sat, Sep 2, 2017 at 1:54 PM, Carlos Scheidegger <notifications@github.com

**Comment by codementum** [comment]
Should this be closed without merging?
I see a page as of two days ago -> https://github.com/ieee-vgtc/ieeevis.org/commits/master/year/2017/info/awards/vast-challenge-awards.md

cc @cscheid @whiting-vastchallenge

**Comment by RossMaciejewski** [comment]
Should be ok to close and merge I think

**Comment by cscheid** [comment]
I think we merged this before. I'm going to close this.

**Pull request closed without merging**
