### PR TITLE
Update fast-forward-and-video-previews.md

### PR DESCRIPTION
**Pull request by hguo**
Updated the call for videos.

### CODE REVIEW

**Comment by cscheid** [comment]
Ok, @hguo, this was a little bigger of a change than I had expected. Can you explain what you were trying to do here?

**Comment by hguo** [comment]
Hi Carlos, 

Tamra suggested us to add a table to clearly show the difference between fast forward and video previews.  She also helped us to edit the wordings.  We are also removing the list of tracks that do not have videos for internal use only.  Thank you.

-Hanqi

---------------
Hanqi Guo

**Comment by cscheid** [comment]
Ok. Can you explain the "Legal" in "Legal Details"?

**Comment by cscheid** [comment]
Also, the only cell that uses rowspan is "format", for which the content is repeated. Any reason for that?

**Comment by hguo** [comment]
Hi Carlos, 

The legal detail is “you must certify that any background audio is free from copyright or that you are licensed to use it”.  The rationale of the colspan is that we use the same video for FF and previews.  

Best, 
Hanqi

---------------
Hanqi Guo

**Comment by cscheid** [comment]
Sure, but the fact that you use the same video was explained in the text before. My question is: why is the content repeated?

**Comment by cscheid** [comment]
I'll merge the pull request (I had to fix a missing </tr> tag, but that's minor)

For what's worth, I don't think this a very clear set of instructions, but I'll let you sort it out :)

**Comment by hguo** [comment]
We do have a bit redundancies in the table to emphasize the similarities and differences between FF and previews.  Any suggestions are welcome, and we are open to change.  Thank you. 

-Hanqi

---------------
Hanqi Guo

**Pull request merged**
