### PR TITLE
Update review-instructions.md

### PR DESCRIPTION
**Pull request by lindstro**

### CODE REVIEW

**Comment by yelper** [comment]
For next time: the anchor tags with names are not needed; your changes to the ToC urls was enough.  Jekyll automatically adds tags to headings.

**Comment by lindstro** [comment]
How does Jekyll translate headings to tags, e.g., how does it handle upper case, spaces, and symbols?  For example, how would I reference a markdown heading named

## What is a Minor Revision?

**Comment by yelper** [comment]
It strips out all puncuation and replaces whitespace with dashes (`-`), so your example would become "what-is-a-minor-revision".

You can check this on staging by checking the "id" of the heading: 
image

**Comment by lindstro** [comment]
I see.  I actually looked at the page source and searched for `name=` but didn't find anything.  I should have looked more closely.  Another concern I had are the multiple identical subheadings, but I see that Jekyll appends a number to make them unique.

If you prefer, I can remove the html tags.

**Comment by yelper** [comment]
No need, I can clean it up.  Let me know if you have further questions!

**Pull request merged**
