### PR TITLE
Add presenter/speaker file via upload/updating

### PR DESCRIPTION
**Pull request by mhaley1979**
adding speakers-and-presenters html for 2017 updating on staging

### CODE REVIEW

**Comment by cscheid** [comment]
This looks like an HTML file of the GitHub webpage. Can you clarify what you're trying to do here?
Thanks.

**Comment by mhaley1979** [comment]
sorry, was quickly trying to make a copy for 2017 from 2016 so i can begin editing it on staging.

**Comment by cscheid** [comment]
It's here now: http://staging.ieeevis.org/year/2017/info/papers

**Comment by mhaley1979** [comment]
thanks, carlos

**Pull request closed without merging**
