### PR TITLE
Update scivis-paper-types.md

### PR DESCRIPTION
**Pull request by jamesAhrens**
Update page to link to scivis short papers CFP.

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you!

**Comment by cscheid** [comment]
Is this something to be urgently pushed to production?

**Comment by jamesAhrens** [comment]
Thanks Carlos. Not urgent but should be done in a week or so.

**Comment by cscheid** [comment]
Ok, we’ll do it on the next cycle then (that should be a week from today.)
-carlos

**Pull request merged**
