### PR TITLE
add DOI if not empty

### PR DESCRIPTION
**Pull request by bilalsal**

### CODE REVIEW

**Comment by cscheid** [comment]
This is great - @mhaley1979, @codementum: what do you think? Did we get a request for DOIs? It'd be nice to have but I'm not sure about the resulting clutter.

**Comment by codementum** [comment]
First thoughts pro/con +/-:

- Clutter could indeed be bad. 
    - Possibly mitigate through links `<a href="...">doi</a>" or abbreviated DOIs if that's a thing?
+ Could lead future searches back to ieeevis pages.

We could always ask in the phone conf...

**Comment by cscheid** [comment]
Good idea.

And, shockingly, I’m possibly going to be available at the call tomorrow!

**Comment by codementum** [comment]
Thanks thanks @bilalsal -- this is now live

**Pull request merged**
