### PR TITLE
Create bids.md

### PR DESCRIPTION
**Pull request by tamaramunzner**
The question is how to handle these documents in terms of menu structure. I'd like to see them as sub-items under the VEC. This will replace the former PDF file, it's better to have this as a real thing in markdown that can get updated incrementally. I'd like to both have an index at the bottom of the VEC page, and to have them as subitems in the menu. There's also another new file, coordination.md, which should also be a subitem.

### CODE REVIEW

**Comment by cscheid** [comment]
If we're creating a new page, I think we should consider getting the URL right. Does it belong in `/info/committees/` and, more to the point, does it belong in `/year/2017/`? Don't you think it makes sense, eg, to have a top-level `/governance` URL?

**Comment by cscheid** [comment]
Incidentally, I _love love love_ the idea of putting this stuff out in the open.

**Comment by tamaramunzner** [comment]
Aha, great idea. Maybe governance would be a great place to put many things! Bids, the InfoVis SC document, the coordination document, etc. I do think these things will frequently change, although not always necessarily in conjunction with year boundaries. I'm not sure of the answer for whether they should live under the year or not, how do we handle this for other stuff?...

**Comment by cscheid** [comment]
Short answer is we currently don't have anything like it, because the previous infrastructure made it a huge pain in the ass to have things that were independent of the yearly cycle. But now it's easy! (Well, "easy": deciding which template to use will be required, but it's certainly eas_ier_.)

**Comment by tamaramunzner** [comment]
OK, can you make a "governance" folder and shove all these things there? I may well add more stuff over the next days, as I'm tying up all the loose ends I'm realizing which things should just get posted publicly instead of being available for organizers only. 

As I'm corresponding with various people this week I'm also realizing that there would be a lot of value in archiving some of these slide decks that get presented in the plenary sessions - the opening session slides for all of VIS, the closing session slides, the per-track opening slides. Let's think about where we should put them too. Should be within the year, maybe just call it "presentations"? I'd love to be able to link to both PPT and PDF versions of each one (the PDF is better for browsing, the PPT is better for future organizers - might as well make this serve a dual purpose instead of having to go hunt down the PPT in later years).

**Comment by cscheid** [comment]
Great - I'll merge these and move to `/governance` on a separate commit. I'll create an issue to track the general problem and I'll cc you.

PDFs and PPTs are fine, but we might start running into issues with large files (>10MB) because git is annoying like that.

**Pull request merged**
