### PR TITLE
Update references to VGTC publications.

### PR DESCRIPTION
**Pull request by arvind**
Fix open practices information as templates have been consolidated.

### CODE REVIEW

**Comment by yelper** [comment]
Do you want to wait for Carlos before merging?

**Comment by arvind** [comment]
Perhaps, since I modified the open practice/arxiv instructions page. @cscheid, I dropped the extra step since the templates we posted on vgtc.org should cover both cases now?

**Comment by cscheid** [comment]
Arvind, that looks correct. Do not that I haven't actually tried it out, and I won't have time to do it this week :( What goes wrong if someone incorrectly follows these instructions? I think they might end up, at worst, with the wrong template. Since VIS is not required to be double-blind (right?) this is... not catastrophic?

Based on this ~~series of guesses~~ Clearly Very Thorough Research, I think we're ok to push.

**Comment by yelper** [comment]
you should see these changes on staging shortly

**Pull request merged**
