### PR TITLE
Update community.md

### PR DESCRIPTION
**Pull request by abezerianos**
Hi Carlos, can we update the Community page (changed the link towards the final Newcomers meetup)

### CODE REVIEW

**Comment by cscheid** [comment]
Done, thanks!

**Comment by abezerianos** [comment]
Ooops Carlos I just saw that the formatting was messed up from the last
change, can i quickly change it (so sorry about this ...)
Thank you for being so proactive!

**Comment by cscheid** [comment]
You can issue a new PR - I don’t know what happens if you amend this directly..

**Comment by abezerianos** [comment]
Thanks Carlos, I issued a new one (not sure what happened between the two
changes with a bullet list, should be ok now).
Sorry again

**Pull request merged**
