### PR TITLE
Add accessibility to the menu and call for participation

### PR DESCRIPTION
**Pull request by domoritz**
Merge after #1470

### CODE REVIEW

**Comment by spetruzza** [comment]
Not sure that we need to merge also the changes to the build

**Comment by domoritz** [comment]
You can merge #1470 first.

**Comment by spetruzza** [comment]
It would be better to have separate PRs for changes to the website content and to the build. This way we can merge updates to the website while testing the new build.

In other words, if we can remove the changes to the build from this PR (which seem to be redundant with other PRs) we can merge the changes on the accessibility content sooner.

**Comment by domoritz** [comment]
No problem. I dropped the commit.

**Pull request merged**
