### PR TITLE
Comment out student volunteers section

### PR DESCRIPTION
**Pull request by jamesAhrens**
It is not part of initial December CFP release and the volunteer information is from 2011!

### CODE REVIEW

**Comment by cscheid** [comment]
Ok - Just to be clear: the student volunteer website is managed by the student volunteers. Do you want me to relay information to them about what to change?

**Comment by jamesAhrens** [comment]
I can send the mail to Sv. I'm on a vacation / drive so my internet goes in and out. So far so good on website changes. Will send "discussion" email later.

Thanks
Jim

________________________________

**Comment by jamesAhrens** [comment]
Also in the left column I tired to comment out the student volunteer links with <--!  Now these characters show up on staging along with the student volunteer and information links - so my attempt at comments did not work. Can you help fix this please?

Thx
Jim

________________________________

**Comment by jamesAhrens** [comment]
It was just the HTML comment syntax that was flipped (instead of “<!—“, you had “<—!”)

Easy fix, it’s done and live on staging.

-carlos

**Pull request merged**
