### PR TITLE
Need to add the Supporter registration link

### PR DESCRIPTION
**Pull request by ARSanderson**
Please see the additions on line 30 - no other changes need to be made.

That said I am open to having the link else where.

### CODE REVIEW

**Comment by cscheid** [comment]
Hi Allen,

this would be redundant with the first link on the page. I'm ok with that, but I want to make sure you didn't overlook that. In the part that says

"Support VIS 2017
You can register as a VIS 2017 supporter by clicking here."

"here" links to the same page you're adding.

**Comment by ARSanderson** [comment]
Hi Carlos,

Are we on the same page?? Where is the first page linked from????


There is the summary page:

http://www.cvent.com/events/2017-ieee-visualization-conference-supporter-vis-/event-summary-d22aeff4b0d54841b2b367fc8178323d.aspx

Which has a link to the registration page:

https://www.cvent.com/events/2017-ieee-visualization-conference-supporter-vis-/registration-d22aeff4b0d54841b2b367fc8178323d.aspx?fqp=true <https://www.cvent.com/events/2017-ieee-visualization-conference-supporter-vis-/registration-d22aeff4b0d54841b2b367fc8178323d.aspx?fqp=true>

The supporter page needs a link to the registration

http://ieeevis.org/year/2017/info/exhibition/supporters-and-exhibition


Cheers,

Allen

**Comment by cscheid** [comment]
Hit shift-reload, maybe? This is what I see:

image

**Comment by ARSanderson** [comment]
Damn caching … I see it now. Okay that works for me. No need to change anything.


Cheers,

Allen

**Comment by codementum** [comment]
@ARSanderson @cscheid Are we clear to close without merging?

**Comment by cscheid** [comment]
Yeah, I'll close this. Thanks.

**Pull request closed without merging**
