### PR TITLE
Update left_sidebar-2017.html

### PR DESCRIPTION
**Pull request by RossMaciejewski**
Had broken link for keynote, please fix soon please, sorry :-(

### CODE REVIEW

**Comment by RossMaciejewski** [comment]
Thanks, can we push it to main too? Sorry :-(

**Comment by cscheid** [comment]
Happening right now.

**Comment by RossMaciejewski** [comment]
Thanks!

**Comment by cscheid** [comment]
Do note that it appears that the keynote page has Georgia Lupi's picture, who is, to my understanding, the capstone speaker.

**Comment by cscheid** [comment]
Links are fixed on staging and production. I'll cc you on the new issue I noticed.

**Comment by RossMaciejewski** [comment]
Argh, ok, going in to fix that.

**Pull request merged**
